version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: jobboard-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

  backend:
    build: ./backend
    container_name: jobboard-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/jobboard
      FRONTEND_ORIGIN: http://localhost:3000

  frontend:
    build: ./frontend
    container_name: jobboard-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_SERVER_URL: http://localhost:5000

volumes:
  mongo_data:
